Test workflow trigger14

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -48,20 +48,27 @@ jobs:
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
+      
+      - name: Check Docker Username
+        run: |
+          if [ -z "$DOCKER_USERNAME" ]; then
+            echo "Error: DOCKER_USERNAME is not set."
+            exit 1
+          fi
 
       - name: Log values
         run: |
           echo "DOCKER_USERNAME: $DOCKER_USERNAME"
           echo "Service: ${{ matrix.service }}"
           echo "GITHUB_SHA: ${{ github.sha }}"
-          
+
       # Build and push Docker image
       - name: Build and push Docker image
         working-directory: services/${{ matrix.service }}
         run: |
           TAG=${{ github.sha }}
-          docker build -t $DOCKER_USERNAME/${{ matrix.service }}:${{ github.sha }} .
-          docker push $DOCKER_USERNAME/${{ matrix.service }}:${{ github.sha }}
+          docker build -t binamin/${{ matrix.service }}:${{ github.sha }} .
+          docker push binamin/${{ matrix.service }}:${{ github.sha }}
 
       # Deploy to Kubernetes
       - name: Deploy to Kubernetes
